import { deleteUserAccountData } from "./firebase/accountService"
import {
  addWordToCollection,
  createCollection,
  deleteCollection,
  getCollections,
  removeWordFromCollection,
  updateCollection,
} from "./firebase/collectionsService"
import {
  addWordToDictionary,
  getUserDictionary,
  onDictionaryChange,
  removeWordFromDictionary,
} from "./firebase/dictionaryService"
import {
  getFlashcardProgress,
  migrateFlashcardData,
  saveFlashcardProgress,
} from "./firebase/flashcardsService"
import {
  createUserProfile,
  getUserCredentials,
  getUserProfile,
  updateUserCredentials,
  updateUserProfile,
} from "./firebase/profilesService"
import {
  getSavedPosts,
  removeSavedPost,
  savePost,
} from "./firebase/savedPostsService"
import {
  blockUser,
  followUser,
  getUserFollowers,
  getUserFollowing,
  isFollowing,
  removeFollower,
  unfollowUser,
} from "./firebase/socialService"
import { searchUsers } from "./firebase/userSearchService"

export {
  createUserProfile,
  getUserProfile,
  updateUserProfile,
  updateUserCredentials,
  getUserCredentials,
  addWordToDictionary,
  removeWordFromDictionary,
  getUserDictionary,
  onDictionaryChange,
  getFlashcardProgress,
  saveFlashcardProgress,
  migrateFlashcardData,
  getSavedPosts,
  savePost,
  removeSavedPost,
  createCollection,
  getCollections,
  updateCollection,
  deleteCollection,
  addWordToCollection,
  removeWordFromCollection,
  isFollowing,
  followUser,
  unfollowUser,
  getUserFollowers,
  getUserFollowing,
  removeFollower,
  blockUser,
  searchUsers,
  deleteUserAccountData,
}

export default {
  createUserProfile,
  getUserProfile,
  updateUserProfile,
  updateUserCredentials,
  getUserCredentials,
  addWordToDictionary,
  removeWordFromDictionary,
  getUserDictionary,
  onDictionaryChange,
  getFlashcardProgress,
  saveFlashcardProgress,
  migrateFlashcardData,
  getSavedPosts,
  savePost,
  removeSavedPost,
  createCollection,
  getCollections,
  updateCollection,
  deleteCollection,
  addWordToCollection,
  removeWordFromCollection,
  searchUsers,
  followUser,
  unfollowUser,
  isFollowing,
  getUserFollowers,
  getUserFollowing,
  removeFollower,
  blockUser,
  deleteUserAccountData,
}
